### ISSUE TITLE
React Native checkout

### ISSUE THREAD

**Issue by Lucasbrunoferreira** [tamojuno/direct-checkout-android#12]
Hello, I am developing a mobile application, with React Native, and I need to use JUNO as a gateway, because the web version we are already using. Is there any solution for react-native?

**Comment by SirFilbido** [comment]
Hi Lucas,
We are happy that you are using our services. Today we do not have support for React Native. We only have for Android (Kotlin), [iOS](https://github.com/tamojuno/direct-checkout-ios) (Swfit) and [Flutter](https://github.com/tamojuno/direct-checkout-flutter) (Dart).
I'll take this idea to Juno's Time Mobile to see if we can support React Native. In a while I will bring you more information.

**Comment by Lucasbrunoferreira** [comment]
Thanks for the feedback, I'm waiting, thanks!

**Comment by Lucasbrunoferreira** [comment]
Hello guys, do you have any news?

**Comment by SirFilbido** [comment]
Hello Lucas,

We talked internally together with the product area and saw that we have no plans to officially release the SDK in React Native.

Remembering that we officially make available the SDKs for Android, iOS and Flutter.
