### ISSUE TITLE
Other Endpoints?

### ISSUE THREAD

**Issue by lcsvcn** [tamojuno/direct-checkout-android#4]
There any plan to implement the rest of the endpoints?

- /credit-cards/tokenization
- /payments
- /payments/{id}/refunds
- /payments/{id}/capture
- /payments/{id}/cancelation
- /charges/{id}/split

I would like to add this to my app using this lib, but need to know if there is some work on it already going.

tks

**Comment by SirFilbido** [comment]
Hi lcsvcn, 

Sorry to just answer now.
Unfortunately we don't have plans and we don't see a necessary requirement for this to be prioritized
