### ISSUE TITLE
Lib para flutter

### ISSUE THREAD

**Issue by gabrielscr** [tamojuno/direct-checkout-android#5]
Pretendem criar uma lib para flutter/dart também? É o que mais está sendo usado no momento

**Comment by rafaeldalbosco** [comment]
> Pretendem criar uma lib para flutter/dart também? É o que mais está sendo usado no momento

Desenvolvi por conta própria @gabrielscr, está no meu repositório, mas não publiquei no flutter packages por questões de tempo: 

https://github.com/rafaeldalbosco/juno_direct_checkout_flutter

adicione no seu pubspec.yaml
```
  juno_direct_checkout:
    git:
      url: https://github.com/rafaeldalbosco/juno_direct_checkout_flutter.git
```

**Comment by gabrielscr** [comment]
muito obrigado, irei testar!

**Comment by diefferson** [comment]
@gabrielscr publiquei a Lib em Flutter disponibilizado pelo nosso colega @rafaeldalbosco  segue o link:
https://pub.dev/packages/juno_direct_checkout
